c_compiler_version:                       # [unix]
  - 12                                    # [osx]
  - 9                                     # [linux]
cxx_compiler_version:                     # [unix]
  - 12                                    # [osx]
  - 9                                     # [linux]
fortran_compiler_version:                 # [unix]
  - 11                                    # [osx and arm64]
  - 9                                     # [osx and x86_64]
  - 9                                     # [linux]
cudnn:                                    # [linux64]
  - None                                  # [linux64]
cuda_compiler_version:                    # [linux64]
  - None                                  # [linux64]
docker_image:                             # [linux64]
  - condaforge/linux-anvil-cos7-x86_64    # [linux64]
cdt_name:                                 # [linux64]
  - cos7                                  # [linux64]
